apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: votingapp.simplon-yuta.space
  namespace: default
spec:
  dnsNames:
  - votingapp.simplon-yuta.space
  issuerRef:
    name: letsencrypt-staging
    kind: Issuer
  secretName: secret-tls
