apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistantyuta2claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: sc-yuta
  volumeName: persistantyuta2
  resources:
    requests:
      storage: 5Gi
