apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: scale-votingapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: votingapp
  minReplicas: 1
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
